---
- name: Install
  hosts: all
  become: true
  become_method: ansible.builtin.sudo

  pre_tasks:
  - name: check for file custom_vars.yml
    stat:
      path: custom_vars.yml
    register: stat_custom_vars
  - name: load custom vars, if existent
    include_vars:
      file: custom_vars.yml
    when: stat_custom_vars.stat.exists

  roles:
  - name: andrelohmann.root_colored_prompt
  - name: ansible-role-maxmind
...
