---
- name: Converge
  hosts: all
  vars:
    maxmind_account_id: __ACCOUNT_ID__
    maxmind_license_key: __LICENSE_KEY__
    maxmind_edition_ids: GeoLite2-ASN GeoLite2-City GeoLite2-Country
    maxmind_geoipupdate_run: false
  tasks:
  - name: "Include andrelohmann.maxmind"
    include_role:
      name: "andrelohmann.maxmind"
...
